spring:
  datasource:
    h2:
      console.enabled: true
    url: jdbc:h2:file:/home/ubuntu/Documents/workspace/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect