INSERT INTO HELLO_WORLD
 (FIRST_NAME , LAST_NAME) VALUES ('TOTO', 'TATA');
INSERT INTO HELLO_WORLD (FIRST_NAME , LAST_NAME) VALUES ('Aymen', 'BENJ');
INSERT INTO HELLO_WORLD (FIRST_NAME , LAST_NAME) VALUES ('AZERTY', 'QWERTY');
INSERT INTO HELLO_WORLD (FIRST_NAME , LAST_NAME) VALUES ('TOTtrezaO', 'DFDFDFD');